const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',

    //language
    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',

    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'ADMIN_LOGIN_FAIL',
    PROCESS_LOGOUT_SUCCESS: 'PROCESS_LOGOUT_SUCCESS',
    PROCESS_LOGOUT_FAIL: 'PROCESS_LOGOUT_FAIL',

    SET_PARAMS_SEARCH: 'SET_PARAMS_SEARCH',

    // admin:

    FETCH_KEY_FORM_SUCCESS: 'FETCH_KEY_FORM_SUCCESS',
    FETCH_KEY_FORM_FAIL: 'FETCH_KEY_FORM_FAIL',

    CREATE_USER_REDUX_SUCCESS: 'CREATE_USER_REDUX_SUCCESS',
    CREATE_USER_REDUX_FAIL: 'CREATE_USER_REDUX_FAIL',

    FETCH_ALL_USER_SUCCESS: 'FETCH_ALL_USER_SUCCESS',
    FETCH_ALL_USER_FAIL: 'FETCH_ALL_USER_FAIL',

    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    DELETE_USER_FAIL: 'DELETE_USER_FAIL',

    UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
    UPDATE_USER_FAIL: 'UPDATE_USER_FAIL',

    FETCH_TOP_DOCTOR_SUCCESS: 'FETCH_TOP_DOCTOR_SUCCESS',
    FETCH_TOP_DOCTOR_FAIL: 'FETCH_TOP_DOCTOR_FAIL',

    FETCH_ALL_DOCTOR_SUCCESS: 'FETCH_ALL_DOCTOR_SUCCESS',
    FETCH_ALL_DOCTOR_FAIL: 'FETCH_ALL_DOCTOR_FAIL',

    SAVE_DETAIL_DOCTOR_SUCCESS: 'SAVE_DETAIL_DOCTOR_SUCCESS',
    SAVE_DETAIL_DOCTOR_FAIL: 'SAVE_DETAIL_DOCTOR_FAIL',

    GET_DETAIL_DOCTOR_SUCCESS: 'GET_DETAIL_DOCTOR_SUCCESS',
    GET_DETAIL_DOCTOR_FAIL: 'GET_DETAIL_DOCTOR_FAIL',

    FETCH_ALLCODE_SCHEDULE_SUCCESS: 'FETCH_ALLCODE_SCHEDULE_SUCCESS',
    FETCH_ALLCODE_SCHEDULE_FAIL: 'FETCH_ALLCODE_SCHEDULE_FAIL',

    SAVE_SCHEDULE_DOCTOR_SUCCESS: 'SAVE_SCHEDULE_DOCTOR_SUCCESS',
    SAVE_SCHEDULE_DOCTOR_FAIL: 'SAVE_SCHEDULE_DOCTOR_FAIL',

    GET_SCHEDULE_DOCTOR_SUCCESS: 'GET_SCHEDULE_DOCTOR_SUCCESS',
    GET_SCHEDULE_DOCTOR_FAIL: 'GET_SCHEDULE_DOCTOR_FAIL',

    FETCH_RELATE_TO_DOCTOR_INFOR_SUCCESS: 'FETCH_RELATE_TO_DOCTOR_INFOR_SUCCESS',
    FETCH_RELATE_TO_DOCTOR_INFOR_FAIL: 'FETCH_RELATE_TO_DOCTOR_INFOR_FAIL',

    POST_BOOKING_APPOINTMENT_SUCCESS: 'POST_BOOKING_APPOINTMENT_SUCCESS',
    POST_BOOKING_APPOINTMENT_FAIL: 'POST_BOOKING_APPOINTMENT_FAIL',

    POST_SPECIALTY_SUCCESS: 'POST_SPECIALTY_SUCCESS',
    POST_SPECIALTY_FAIL: 'POST_SPECIALTY_FAIL',

    GET_ALL_SPECIALTY_SUCCESS: 'GET_ALL_SPECIALTY_SUCCESS',
    GET_ALL_SPECIALTY_FAIL: 'GET_ALL_SPECIALTY_FAIL',

    GET_ALL_CLINIC_SUCCESS: 'GET_ALL_CLINIC_SUCCESS',
    GET_ALL_CLINIC_FAIL: 'GET_ALL_CLINIC_FAIL',

    GET_ALL_HANDBOOK_SUCCESS: 'GET_ALL_HANDBOOK_SUCCESS',
    GET_ALL_HANDBOOK_FAIL: 'GET_ALL_HANDBOOK_FAIL',

    GET_APPOINTMENT_DOCTOR_SUCCESS: 'GET_APPOINTMENT_DOCTOR_SUCCESS',
    GET_APPOINTMENT_DOCTOR_FAIL: 'GET_APPOINTMENT_DOCTOR_FAIL',

    CHANGE_PROVINCE_SUCCESS: 'CHANGE_PROVINCE_SUCCESS',
    CHANGE_PROVINCE_FAIL: 'CHANGE_PROVINCE_FAIL',

    CHANGE_STATUS_SUCCESS: 'CHANGE_STATUS_SUCCESS',
    CHANGE_STATUS_FAIL: 'CHANGE_STATUS_FAIL',

    GET_QUEUE_NEW_SUCCESS: 'GET_QUEUE_NEW_SUCCESS',
    GET_QUEUE_NEW_FAIL: 'GET_QUEUE_NEW_FAIL',

    GET_DETAIL_USER_SUCCESS: 'GET_DETAIL_USER_SUCCESS',
    GET_DETAIL_USER_FAIL: 'GET_DETAIL_USER_FAIL',

    GET_QUEUE_HANDBOOK_SUCCESS: 'GET_QUEUE_HANDBOOK_SUCCESS',
    GET_QUEUE_HANDBOOK_FAIL: 'GET_QUEUE_HANDBOOK_FAIL',
});

export default actionTypes;
